/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.aau;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {

    private Stage primaryStage;
    private BorderPane menu;

    /**
     * Initializes the Menu.
     */
    public void initMenu() {
        try {
            // Load Menu from fxml file.
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getResource("/Menu.fxml"));
            menu = (BorderPane) loader.load();
            
            // Show the scene containing the root layout.
            Scene scene = new Scene(menu);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    @Override
    public void start(Stage primaryStage) throws Exception {
        // TODO Auto-generated method stub
    }
    public static void main(String[] args) {
       launch(args);
    }
}