/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dk.aau;

import java.io.IOException;

import dk.aau.address.view.MenuController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {

    private Stage primaryStage;
    private BorderPane rootLayout;

    public App(){
        //Tilføj noget data her
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage;
        this.primaryStage.setTitle("GenitalProlapsApp");

        initRootlayout();
        showMenuOverview();

    }
    
    /**
     * Initializes the RootLayout.
     */
    public void initRootlayout() {
        try {
            // Load root layout from fxml file.
            FXMLLoader loader = new FXMLLoader();
            loader.setLocation(App.class.getResource("/RootLayout.fxml"));
            rootLayout = (BorderPane) loader.load();
            
            // Show the scene containing the root layout.
            Scene scene = new Scene(rootLayout);
            primaryStage.setScene(scene);
            primaryStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     * Shows the Menu inside the root layout
     */
    public void showMenuOverview(){
        try{
        // Load person overview.
        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(App.class.getResource("/Menu.fxml"));
        AnchorPane menuOverview = (AnchorPane) loader.load();
        
        // Set person overview into the center of root layout.
        rootLayout.setCenter(menuOverview);

        // Give the controller access to the main app.
        MenuController controller = loader.getController();
        controller.setApp(this);

    } catch (IOException e) {
        e.printStackTrace();
    }
    }

    /**
     * Returns the main stage.
     * @return
     */
    public Stage getPrimaryStage() {
        return primaryStage;
    }

    public static void main(String[] args) {
       launch(args);
    }
}